### ISSUE TITLE
Urllib-Error running main.exe

### ISSUE THREAD

**Issue by PetrosStavrakakis** [Petrosz007/goblineer-updater#1]
Hi Petros,

After modifying the config.json to my needs the main.exe bails out with the following exception:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "downloader.py", line 7, in get_latest_data
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 532, in open
  File "urllib\request.py", line 642, in http_response
  File "urllib\request.py", line 570, in error
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 400: BAD_REQUEST
[12868] Failed to execute script main

I checked the function "get_latest_data" and recreated the URL manually with my configuration and tested it directly in a Firefox Browser. Worked perfectly.

Do you need something else?

Regards,
Petros

**Comment by PetrosStavrakakis** [comment]
Hi Petros,
Petros here again.

I found the Problem.
I am on a server with spaces in the realm name: "Die Silberne Hand".
I had to replace the spaces with %20 and build the url with that realm string:

```
def get_latest_data(region, realm, api_key):
    mod_realm=realm.replace(" ","%20");
    url = "https://" + region + ".api.battle.net/wow/auction/data/" + mod_realm + "?locale=en_GB&apikey=" + api_key;
    response = urllib.request.urlopen(url)
    data = json.load(response)

    return data["files"][0]
```

Regards,
Petros

**Comment by Petrosz007** [comment]
Hi Petros.

The Blizzard API uses "slugs" instead of full server names, those are basically the server's name all lower case, spaces are replaced with `-`s. Special characters like `'` are just removed, and special letters like `á é` become their corresponding version in the English alphabet, in this case `a e`.

Example: `Die Silberne Hand` becomes `die-silberne-hand` and `Pozzo dell'Eternità` becomes `pozzo-delleternita`.

You should use this "slug" version of the server name in `config.json`.


Thanks for bringing this up, I'll add it to the Readme.
